import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import Login from "@/container/Login";
import { useEffect, useState } from "react";
import axios from "axios";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [posts, setPosts] = useState([]);

  var config = {
    method: "get",
    maxBodyLength: Infinity,
    url: `${process.env.NEXT_PUBLIC_API_URL}/api/v1/blog/getall`,
    headers: {},
  };

  const fetchBlog = async () => {
    axios(config)
      .then(function (response) {
        setPosts(response.data.data);
      })
      .catch(function (error) {
        console.log(error);
      });
  };

  useEffect(() => {
    fetchBlog();
  }, []);
  return (
    <>
      <Head>
        <title>Foster Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Login />
      </div>
    </>
  );
}
